version: '3.8'
services:
  api:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rehearsal
      POSTGRES_PASSWORD: rehearsalpass
      POSTGRES_DB: rehearsaldb
    volumes:
      - dbdata:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
volumes:
  dbdata:
